steps:

# This step deploys the stage application in Kubernetes
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=stage.yaml
  - --image=gcr.io/$PROJECT_ID/constellationweb:$_SHORT_SHA
  - --output=/tmp/outputstage
  - --location=us-east1-b
  - --cluster=cluster-1 
  
  
# This step runs the ConstellationTests Image 
# The PROJECT_ID variable is automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: run
  env:
  - 'NODE_ENV=stage'
  args:
  - 'run'
  - 'gcr.io/$PROJECT_ID/constellationautotest:latest'
  - 'npm'
  - 'run'
  - 'test-test'

# This step deploys the prod application in Kubernetes
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - builds
   - submit
   - --config
   - cloudbuild-prod.yaml
   - --substitutions
   - _SHORT_SHA=$_SHORT_SHA
   - .
 