steps:

# This step deploys the dev application in Kubernetes
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=prod.yaml
  - --image=gcr.io/$PROJECT_ID/constellationweb:$_SHORT_SHA
  - --location=us-east1-b
  - --cluster=cluster-1  
  env:
  - KUBECONFIG=/tmp/kubeconfig




