steps:

# This step deploys the dev application in Kubernetes
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=prod.yaml
  - --image=gcr.io/$PROJECT_ID/constellationweb:$_SHORT_SHA
  - --output=/tmp/outputprod
  - --location=us-east1-b
  - --cluster=cluster-1  


  - name: 'gcr.io/cloud-builders/gcloud'
  id: Trigger Dev Integration Tests
  args:
  - 'beta'
  - 'builds'
  - 'triggers'
  - 'run'
  - 'a2b3e35c-62d3-479c-8385-c41d5b8e0228'
  - '--branch=master'

