steps:

# This step deploys the stage application in Kubernetes
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=stage.yaml
  - --image=gcr.io/$PROJECT_ID/constellationweb:$_SHORT_SHA
  - --output=/tmp/outputstage
  - --location=us-east1-b
  - --cluster=cluster-1 
  
  
- name: 'gcr.io/cloud-builders/gcloud'
  id: Trigger Stage Integration Tests
  args:
  - 'beta'
  - 'builds'
  - 'triggers'
  - 'run'
  - 'a2b3e35c-62d3-479c-8385-c41d5b8e0228'
  - '--branch=master'

# # This step deploys the prod application in Kubernetes
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - builds
#   - submit
#   - --config
#   - cloudbuild-prod.yaml
#   - --substitutions
#   - _SHORT_SHA=$_SHORT_SHA
#   - .
 