apiVersion: apps/v1
kind: Deployment
metadata:
  name: constellationprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: constellationprod
  template:
    metadata:
      labels:
        app: constellationprod
    spec:
      containers:
      - name: constellationprod
        image: gcr.io/constellation-275522/constellationweb
        ports:
        - containerPort: 80
        env:
          - name: CUSTOMCONNSTR_ConstellationWebAppContext
          valueFrom:
            secretKeyRef:
              name: prod-app-settings
              key: web-app-context
        - name: ASPNETCORE_ENVIRONMENT
          value: production
        resources:
          limits:
            cpu: "1"
            memory: "1000Mi"
          requests:
            cpu: ".25"
            memory: "250Mi"
        volumeMounts:
        - name: image
          mountPath: /app/wwwroot/image
        - name: resumes
          mountPath: /app/wwwroot/Resumes
        livenessProbe:
          httpGet:
            path: /account/login
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
      - name: image
        persistentVolumeClaim:
          claimName: constellationprod-image-claim
      - name: resumes
        persistentVolumeClaim:
          claimName: constellationprod-resumes-claim
---
apiVersion: v1
kind: Service
metadata:
  name: constellationprod
spec:
  selector:
    app: constellationprod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: constellationprod-loadbalancer
spec:
  selector:
    app: constellationprod
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: constellationprod-image
  labels:
    name: constellationprod-image
spec:
  accessModes:
   - ReadWriteMany
  capacity:
    storage: 5Gi
  mountOptions:
   - hard
   - nfsvers=4.1
  nfs:
    path: /images
    server: 10.12.15.212
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: constellationprod-resumes
  labels:
    name: constellationprod-resumes
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.12.15.212
    path: /resumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: constellationprod-resumes-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: "constellationprod-resumes"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: constellationprod-image-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: "constellationprod-image"

