apiVersion: apps/v1
kind: Deployment
metadata:
  name: constellationstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: constellationstage
  template:
    metadata:
      labels:
        app: constellationstage
    spec:
      containers:
      - name: constellationstage
        image: gcr.io/constellation-275522/constellationweb
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: staging
        resources:
          limits:
            cpu: "1"
            memory: "1000Mi"
          requests:
            cpu: ".25"
            memory: "250Mi"
        volumeMounts:
        - name: image
          mountPath: /app/wwwroot/image
        - name: resumes
          mountPath: /app/wwwroot/Resumes
        livenessProbe:
          httpGet:
            path: /account/login
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
      - name: image
        persistentVolumeClaim:
          claimName: constellationstage-image-claim
      - name: resumes
        persistentVolumeClaim:
          claimName: constellationstage-resumes-claim
---
apiVersion: v1
kind: Service
metadata:
  name: constellationstage
spec:
  selector:
    app: constellationstage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: constellationstage-loadbalancer
spec:
  selector:
    app: constellationstage
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: constellationstage-image
  labels:
    name: constellationstage-image
spec:
  accessModes:
   - ReadWriteMany
  capacity:
    storage: 5Gi
  mountOptions:
   - hard
   - nfsvers=4.1
  nfs:
    path: /images
    server: 10.12.9.14
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: constellationstage-resumes
  labels:
    name: constellationstage-resumes
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.12.9.14
    path: /resumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: constellationstage-resumes-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: "constellationstage-resumes"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: constellationstage-image-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: "constellationstage-image"
